#!/bin/bash
# Author: Laszlo SERDET

command="./my_radar tests/configs/6_planes_2_towers.rdr"
vg_errors=1 ; vg_contexts=1 ; signal=0 ; path="valgrind-logs"

echo -ne "[\033[1;33mTEST\033[0m] valgrind \t\t\t" ;
if make &> /dev/null ; [ $? -gt 0 ]; then
    echo -e "\033[1;31mFAILED\033[0m" ; exit 1
fi

function cleanup { rm -rf $path vg_errors ; make fclean &> /dev/null ; }
function child { return $(valgrind $command &> $path) ; } ; child &> /dev/null ; signal=$?

if [ $signal -gt 128 ]; then
    echo -e "\033[1;31mCRASH\033[0m" ; cleanup ; exit $signal
fi

vg_errors=$(cat $path | grep "contexts" | cut -d' ' -f4)
vg_contexts=$(cat $path | grep "contexts" | cut -d' ' -f7)

if [ $vg_errors -ne 0 ] && [ $vg_contexts -ne 0 ] || [ -z "$(cat $path | grep "no leaks are possible")" ]; then
    echo -e "\033[1;31mFAILED\033[0m" ; cleanup ; exit 1
fi

echo -e "\033[1;32mPASSED\033[0m" ; cleanup ; exit 0
